
import java.awt.*;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.util.Vector;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.*;
import javax.swing.JFrame;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Tech Trick
 */
public class Bookcard extends javax.swing.JFrame {
    boolean ts = false ; 
    Vector<Integer> favBooks;
    boolean exists;
    int bookId;
    public Bookcard() {
        initComponents();
        bookId = Library.getChoosedBook();
        
        favBooks = Library.getFavBooks();
        for(int i: favBooks) {
            System.out.println("card: "+ i);
        }
        
        exists = favBooks.contains(bookId);
        if(exists) { 
            star.setIcon(new ImageIcon("src/imgs/fullstar.png"));
        } else {
            star.setIcon(new ImageIcon("src/imgs/emptystar.png"));
        }
        loaded();
    }
    
    public void loaded() {
        String path = Library.getChoosedBookPath();
        
        try{
            Tools.connectionToSql() ; 
            System.out.println(bookId);

            String sql = "SELECT * FROM books WHERE id='"+bookId+"';"; 
            ResultSet rs = Tools.selectQuery(sql) ; 
            while(rs.next()){
                name.setText(rs.getString(2));
                authorName.setText(rs.getString(6));
                language.setText(rs.getString(5));
                genre.setText(rs.getString(4));
                cntPages.setText(rs.getString(9));
                rate.setText(rs.getString(7));

                imgShow.setIcon(imgScale(path));

                price.setText(rs.getString(8) + '$');
            }
            Tools.closeConnection();
        } catch(Exception e){}
    }

    public ImageIcon imgScale(String imgPath){
        System.out.println("Bookcard.imgScale()");
        System.out.println(imgShow.getWidth() + " " + imgShow.getHeight());

        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(200, 290,Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    
    private void starMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_starMouseClicked
        String rs = "";
        if(exists) {
            star.setIcon(new ImageIcon("src/imgs/emptystar.png"));
            exists = false;
            favBooks.remove(favBooks.indexOf(bookId));
            for(int i: favBooks) {
                rs += i;
                rs += ',';
            }

        } else {
            star.setIcon(new ImageIcon("src/imgs/fullstar.png"));
            exists = true;
            favBooks.add(bookId);
            rs = "";
            for(int i: favBooks) {
                rs += i;
                rs += ',';
            }
        }
        try{
            String st = "UPDATE persons SET favBooks='"+rs+"' WHERE id='"+Library.getLoginId()+"';";
            System.out.println(rs);
            Tools.excecuateStatement(st);
            Tools.closeConnection();

        } catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_starMouseClicked
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlebar = new javax.swing.JPanel();
        iconminmaxclose = new javax.swing.JPanel();
        Buttonclose = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        ButtonMin = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        price = new javax.swing.JLabel();
        authorName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        language = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        genre = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cntPages = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        AddCard = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        imgShow = new javax.swing.JLabel();
        star = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        titlebar.setBackground(new java.awt.Color(83, 103, 255));
        titlebar.setPreferredSize(new java.awt.Dimension(600, 40));
        titlebar.setLayout(new java.awt.BorderLayout());

        iconminmaxclose.setBackground(new java.awt.Color(83, 103, 255));
        iconminmaxclose.setPreferredSize(new java.awt.Dimension(150, 50));
        iconminmaxclose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buttonclose.setBackground(new java.awt.Color(83, 103, 255));
        Buttonclose.setLayout(new java.awt.BorderLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete_32px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        Buttonclose.add(close, java.awt.BorderLayout.CENTER);

        iconminmaxclose.add(Buttonclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 40));

        ButtonMin.setBackground(new java.awt.Color(83, 103, 255));
        ButtonMin.setLayout(new java.awt.BorderLayout());

        minimize.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        minimize.setForeground(new java.awt.Color(242, 242, 242));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        ButtonMin.add(minimize, java.awt.BorderLayout.CENTER);

        iconminmaxclose.add(ButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 40));

        titlebar.add(iconminmaxclose, java.awt.BorderLayout.LINE_END);

        getContentPane().add(titlebar, java.awt.BorderLayout.PAGE_END);

        main.setBackground(new java.awt.Color(38, 42, 66));
        main.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        main.setName(""); // NOI18N
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        name.setForeground(new java.awt.Color(242, 242, 242));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Book Name");
        main.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 810, 70));

        jPanel4.setBackground(new java.awt.Color(76, 165, 92));
        jPanel4.setLayout(new java.awt.BorderLayout());

        price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        price.setForeground(new java.awt.Color(242, 242, 242));
        price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price.setText("200$");
        jPanel4.add(price, java.awt.BorderLayout.CENTER);

        main.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        authorName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        authorName.setForeground(new java.awt.Color(242, 242, 242));
        authorName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorName.setText("Author Name");
        authorName.setToolTipText("");
        main.add(authorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 131, 149));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Author :");
        jLabel5.setToolTipText("");
        main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(118, 131, 149));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Language :");
        jLabel6.setToolTipText("");
        main.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        language.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        language.setForeground(new java.awt.Color(242, 242, 242));
        language.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        language.setText("English");
        language.setToolTipText("");
        main.add(language, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(118, 131, 149));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Genre :");
        jLabel8.setToolTipText("");
        main.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        genre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        genre.setForeground(new java.awt.Color(242, 242, 242));
        genre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genre.setText("Type");
        genre.setToolTipText("");
        main.add(genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(118, 131, 149));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pages :");
        jLabel10.setToolTipText("");
        main.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        cntPages.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cntPages.setForeground(new java.awt.Color(242, 242, 242));
        cntPages.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cntPages.setText("80");
        cntPages.setToolTipText("");
        main.add(cntPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(118, 131, 149));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Rate :");
        jLabel12.setToolTipText("");
        main.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        rate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rate.setForeground(new java.awt.Color(242, 242, 242));
        rate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rate.setText("4.5");
        rate.setToolTipText("");
        main.add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        AddCard.setBackground(new java.awt.Color(76, 165, 92));
        AddCard.setLayout(new java.awt.BorderLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(242, 242, 242));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Buy");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        AddCard.add(jLabel14, java.awt.BorderLayout.CENTER);

        main.add(AddCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 190, 60));

        imgShow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        main.add(imgShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 200, 290));

        star.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/emptystar.png"))); // NOI18N
        star.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                starMouseClicked(evt);
            }
        });
        main.add(star, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 410, 25, 30));

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        changecolor(Buttonclose, new Color(25, 29, 74));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        changecolor(Buttonclose, new Color(83,103,255));
    }//GEN-LAST:event_closeMouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setExtendedState(Bookcard.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        changecolor(ButtonMin, new Color(25, 29, 74));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        changecolor(ButtonMin, new Color(83,103,255));
    }//GEN-LAST:event_minimizeMouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        changecolor(AddCard, new Color(118,131,149));
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        changecolor(AddCard, new Color(76,165,92));
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
                JOptionPane.showMessageDialog(null, "Done, Item is now yours.");
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookcard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddCard;
    private javax.swing.JPanel ButtonMin;
    private javax.swing.JPanel Buttonclose;
    private javax.swing.JLabel authorName;
    private javax.swing.JLabel close;
    private javax.swing.JLabel cntPages;
    private javax.swing.JLabel genre;
    private javax.swing.JPanel iconminmaxclose;
    private javax.swing.JLabel imgShow;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel language;
    private javax.swing.JPanel main;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel name;
    private javax.swing.JLabel price;
    private javax.swing.JLabel rate;
    private javax.swing.JLabel star;
    private javax.swing.JPanel titlebar;
    // End of variables declaration//GEN-END:variables

    private ImageIcon createImageIcon(String dLibrarysrcimgsfullstarpng) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
