

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Panel;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.border.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;
import java.awt.ScrollPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Peter
 */
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
public class inMain extends javax.swing.JInternalFrame {

    /**
     * Creates new form Main
     */
    public inMain() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui =  (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        Main.setBorder(new EmptyBorder(10, 200 , 10, -10));
        GridLayout layout = new GridLayout(0,3, 30, 20);
        Main.setLayout(layout);
        
        String genere = Library.getGenere();
        String condition = "";  
        
        
        if(!"All".equals(genere)) {
            condition = "WHERE genere='"+genere+"';";
        }
        System.out.println(condition);
        String sql = "SELECT * FROM books "+condition+";";
        try{
            Tools.connectionToSql();
            ResultSet rs = Tools.selectQuery(sql);
            while(rs.next()) {
                int i = rs.getInt(1);
                JLabel label = new JLabel();
                label.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));

                String path = rs.getString(3);
                label.setIcon(ResizeImage(path));
                final int buttonIndex = i;
                label.addMouseListener(new MouseAdapter() {
                   public void mouseClicked(MouseEvent e) {
                       Library.setChoosedBook(buttonIndex);
                       Library.setChoosedBookPath(path);
                       Bookcard ob = new Bookcard() ; 
                       ob.setVisible(true);
                   }
                });
                setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                setVisible(true);
                Main.add(label);
            }
            Tools.closeConnection();


        } catch(Exception ex) {
            ex.printStackTrace();
        }
        
        
        
        JScrollPane scp = new JScrollPane(Main,
            JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,
            JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        
        scp.setAlignmentX(RIGHT_ALIGNMENT);
        add(scp);
        
        
    }
    private ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(300, 400,Image.SCALE_SMOOTH);
        
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1003, 710));

        Main.setBackground(new java.awt.Color(38, 42, 66));
        Main.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Main.setMinimumSize(new java.awt.Dimension(600, 600));
        Main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MainMouseEntered(evt);
            }
        });
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_MainMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    // End of variables declaration//GEN-END:variables
}
