/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Panel;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.border.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;
import java.awt.ScrollPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ThinkPad
 */

public class Mainmenu extends javax.swing.JFrame {
    
    
    boolean a = false;
    Color x = new Color(16,94,195) ;
    JScrollPane scp;

    public Mainmenu() {
        
        this.setExtendedState(Mainmenu.MAXIMIZED_BOTH);
        try
        {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
                if("Windows".equals(info.getName())){
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
            }
        }catch(Exception ex){
            
        }
        initComponents(); 
        Library.setMenuu(this);
        Library.initFavBooks();
        inMain All = new inMain();
        Main.removeAll();
        Main.add(All).setVisible(true);
        All.setBounds(0, 0, Main.getWidth(), Main.getHeight());
    }
    
    private ImageIcon ResizeImage(String imgPath){
        
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(300, 400,Image.SCALE_SMOOTH);
        
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    
    private static class RoundedBorder implements Border {
        
        private int radius;
        
        RoundedBorder(int radius) {
            this.radius = radius;
        }
        @Override
        public Insets getBorderInsets(Component c) {
            return new Insets(this.radius+1, this.radius+1, this.radius+2, this.radius);
        }

        @Override
        public boolean isBorderOpaque() {
            return true;
        }

        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            g.drawRoundRect(x,y,width-1,height-1,radius,radius);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        scrollbar1 = new java.awt.Scrollbar();
        jPanel1 = new javax.swing.JPanel();
        dashboardview = new javax.swing.JPanel();
        titlebar = new javax.swing.JPanel();
        iconminmaxclose = new javax.swing.JPanel();
        Buttonclose = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        Buttonmax = new javax.swing.JPanel();
        fullmax = new javax.swing.JLabel();
        ButtonMin = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        viewProfile = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        panel5 = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        panel6 = new javax.swing.JPanel();
        label6 = new javax.swing.JLabel();
        panel7 = new javax.swing.JPanel();
        label7 = new javax.swing.JLabel();
        panel8 = new javax.swing.JPanel();
        label8 = new javax.swing.JLabel();
        panel9 = new javax.swing.JPanel();
        label9 = new javax.swing.JLabel();
        panel10 = new javax.swing.JPanel();
        label10 = new javax.swing.JLabel();
        panel11 = new javax.swing.JPanel();
        label11 = new javax.swing.JLabel();
        panel12 = new javax.swing.JPanel();
        label12 = new javax.swing.JLabel();
        Main = new javax.swing.JDesktopPane();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        dashboardview.setBackground(new java.awt.Color(73, 128, 242));
        dashboardview.setLayout(new java.awt.BorderLayout());

        titlebar.setBackground(new java.awt.Color(83, 103, 255));
        titlebar.setPreferredSize(new java.awt.Dimension(800, 40));
        titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                titlebarMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                titlebarMouseReleased(evt);
            }
        });
        titlebar.setLayout(new java.awt.BorderLayout());

        iconminmaxclose.setBackground(new java.awt.Color(83, 103, 255));
        iconminmaxclose.setPreferredSize(new java.awt.Dimension(150, 50));
        iconminmaxclose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buttonclose.setBackground(new java.awt.Color(83, 103, 255));
        Buttonclose.setLayout(new java.awt.BorderLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete_32px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        Buttonclose.add(close, java.awt.BorderLayout.CENTER);

        iconminmaxclose.add(Buttonclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 40));

        Buttonmax.setBackground(new java.awt.Color(83, 103, 255));
        Buttonmax.setLayout(new java.awt.BorderLayout());

        fullmax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullmax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/full_screen_32px.png"))); // NOI18N
        fullmax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullmaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fullmaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fullmaxMouseExited(evt);
            }
        });
        Buttonmax.add(fullmax, java.awt.BorderLayout.CENTER);

        iconminmaxclose.add(Buttonmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 40));

        ButtonMin.setBackground(new java.awt.Color(83, 103, 255));
        ButtonMin.setLayout(new java.awt.BorderLayout());

        minimize.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        minimize.setForeground(new java.awt.Color(242, 242, 242));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        ButtonMin.add(minimize, java.awt.BorderLayout.CENTER);

        iconminmaxclose.add(ButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        titlebar.add(iconminmaxclose, java.awt.BorderLayout.LINE_END);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 16));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        titlebar.add(jLabel3, java.awt.BorderLayout.LINE_START);

        viewProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewProfile.setForeground(new java.awt.Color(242, 242, 242));
        viewProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1564535_customer_user_userphoto_account_person_icon.png"))); // NOI18N
        viewProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewProfile.setPreferredSize(new java.awt.Dimension(150, 50));
        viewProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewProfileMouseClicked(evt);
            }
        });
        titlebar.add(viewProfile, java.awt.BorderLayout.CENTER);

        dashboardview.add(titlebar, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(dashboardview, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        Header.setBackground(new java.awt.Color(83, 103, 255));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(83, 103, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new java.awt.BorderLayout());

        Icon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Icon.setForeground(new java.awt.Color(242, 242, 242));
        Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon.setText("BookStore");
        Icon.setToolTipText("");
        Icon.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel2.add(Icon, java.awt.BorderLayout.LINE_START);

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/favourites.png"))); // NOI18N
        jLabel1.setText("Favourites  ");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, java.awt.BorderLayout.LINE_END);

        Header.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        sidebar.setBackground(new java.awt.Color(12, 15, 33));
        sidebar.setPreferredSize(new java.awt.Dimension(200, 410));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(35, 40, 72));
        panel1.setLayout(new java.awt.BorderLayout());

        label1.setBackground(new java.awt.Color(160, 166, 204));
        label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(160, 166, 204));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("All");
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label1MouseExited(evt);
            }
        });
        panel1.add(label1, java.awt.BorderLayout.CENTER);

        sidebar.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 170, 40));

        panel2.setBackground(new java.awt.Color(35, 40, 72));
        panel2.setLayout(new java.awt.BorderLayout());

        label2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(160, 166, 204));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("Fantasy");
        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label2MouseExited(evt);
            }
        });
        panel2.add(label2, java.awt.BorderLayout.CENTER);

        sidebar.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 65, 170, 40));

        panel3.setBackground(new java.awt.Color(35, 40, 72));
        panel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel3.setLayout(new java.awt.BorderLayout());

        label3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(160, 166, 204));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("Mystery");
        label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label3MouseExited(evt);
            }
        });
        panel3.add(label3, java.awt.BorderLayout.CENTER);

        sidebar.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 120, 170, 40));

        panel4.setBackground(new java.awt.Color(35, 40, 72));
        panel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel4.setLayout(new java.awt.BorderLayout());

        label4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(160, 166, 204));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("Science");
        label4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label4MouseExited(evt);
            }
        });
        panel4.add(label4, java.awt.BorderLayout.CENTER);

        sidebar.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, 170, 40));

        panel5.setBackground(new java.awt.Color(35, 40, 72));
        panel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel5.setLayout(new java.awt.BorderLayout());

        label5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(160, 166, 204));
        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5.setText("Politics");
        label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label5MouseExited(evt);
            }
        });
        panel5.add(label5, java.awt.BorderLayout.CENTER);

        sidebar.add(panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 240, 170, 40));

        panel6.setBackground(new java.awt.Color(35, 40, 72));
        panel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel6.setLayout(new java.awt.BorderLayout());

        label6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(160, 166, 204));
        label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label6.setText("Poetry");
        label6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label6MouseExited(evt);
            }
        });
        panel6.add(label6, java.awt.BorderLayout.CENTER);

        sidebar.add(panel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 300, 170, 40));

        panel7.setBackground(new java.awt.Color(35, 40, 72));
        panel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel7.setLayout(new java.awt.BorderLayout());

        label7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label7.setForeground(new java.awt.Color(160, 166, 204));
        label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label7.setText("History");
        label7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label7MouseExited(evt);
            }
        });
        panel7.add(label7, java.awt.BorderLayout.CENTER);

        sidebar.add(panel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 360, 170, 40));

        panel8.setBackground(new java.awt.Color(35, 40, 72));
        panel8.setLayout(new java.awt.BorderLayout());

        label8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label8.setForeground(new java.awt.Color(160, 166, 204));
        label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label8.setText("Computer Science");
        label8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label8MouseExited(evt);
            }
        });
        panel8.add(label8, java.awt.BorderLayout.CENTER);

        sidebar.add(panel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 420, 170, 40));

        panel9.setBackground(new java.awt.Color(35, 40, 72));
        panel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel9.setLayout(new java.awt.BorderLayout());

        label9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label9.setForeground(new java.awt.Color(160, 166, 204));
        label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label9.setText("Novels");
        label9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label9MouseExited(evt);
            }
        });
        panel9.add(label9, java.awt.BorderLayout.CENTER);

        sidebar.add(panel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 480, 170, 40));

        panel10.setBackground(new java.awt.Color(35, 40, 72));
        panel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel10.setLayout(new java.awt.BorderLayout());

        label10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label10.setForeground(new java.awt.Color(160, 166, 204));
        label10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label10.setText("Horror");
        label10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label10MouseExited(evt);
            }
        });
        panel10.add(label10, java.awt.BorderLayout.CENTER);

        sidebar.add(panel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 540, 170, 40));

        panel11.setBackground(new java.awt.Color(35, 40, 72));
        panel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel11.setLayout(new java.awt.BorderLayout());

        label11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label11.setForeground(new java.awt.Color(160, 166, 204));
        label11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label11.setText("Romance");
        label11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label11MouseExited(evt);
            }
        });
        panel11.add(label11, java.awt.BorderLayout.CENTER);

        sidebar.add(panel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 600, 170, 40));

        panel12.setBackground(new java.awt.Color(35, 40, 72));
        panel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel12.setLayout(new java.awt.BorderLayout());

        label12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label12.setForeground(new java.awt.Color(160, 166, 204));
        label12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label12.setText("Arts");
        label12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label12MouseExited(evt);
            }
        });
        panel12.add(label12, java.awt.BorderLayout.CENTER);

        sidebar.add(panel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 660, 170, 40));

        getContentPane().add(sidebar, java.awt.BorderLayout.LINE_START);

        Main.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1247, 846));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void treelist(String folderfile){
        
    }
/*
    
//    public void openpdf (String file){
//        try {
//            SwingController ctrl = new SwingController();
//            SwingViewBuilder vb = new SwingViewBuilder(ctrl);
//            JPanel s = vb.buildViewerPanel();
//            ComponentKeyBinding.install(ctrl, s);
//            ctrl.getDocumentViewController().setAnnotationCallback(
//            new org.icepdf.ri.common.MyAnnotationCallback(ctrl.getDocumentViewController())
//            );
//            ctrl.openDocument(file);
//            
//            dashboardview.add(s);
//        }
//        catch (Exception e){
//            
//        }
//    }
    */
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        if(numberbool == 1){
            h1.setBackground(new Color(25, 29, 74));
            h2.setBackground(new Color(5, 10, 46));
        }
        else{
            h1.setBackground(new Color(5, 10, 46));
            h2.setBackground(new Color(25, 29, 74));
        }
    }
    
    public void changeimage(JLabel button, String resourcheimg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
        button.setIcon(aimg);
    }
    
    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button){
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            changeimage(button, "/Icon/menu_32px.png");
        }
        else{
            menushowhide.setPreferredSize(new Dimension(270, menushowhide.getHeight()));
            changeimage(button, "/Icon/back_32px.png");
        }
        
    }
    

   
    
    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
        Library.setGenere("All");
        inMain All = new inMain();
        Main.removeAll();
        Main.add(All).setVisible(true);
        All.setBounds(0, 0, Main.getWidth(), Main.getHeight());
    }//GEN-LAST:event_label1MouseClicked

    private void label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseClicked
        Library.setGenere("Fantasy");
        inMain All = new inMain();
        Main.removeAll();
        Main.add(All).setVisible(true);
        All.setBounds(0, 0, Main.getWidth(), Main.getHeight());
    }//GEN-LAST:event_label2MouseClicked

    private void label3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MouseClicked
        Library.setGenere("Mystery");
        inMain All = new inMain();
        Main.removeAll();
        Main.add(All).setVisible(true);
        All.setBounds(0, 0, Main.getWidth(), Main.getHeight());
    }//GEN-LAST:event_label3MouseClicked

    private void label4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MouseClicked
        Library.setGenere("Science");
        inMain All = new inMain();
        Main.removeAll();
        Main.add(All).setVisible(true);
        All.setBounds(0, 0, Main.getWidth(), Main.getHeight());
    }//GEN-LAST:event_label4MouseClicked
    
    private void label5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MouseClicked
        Library.setGenere("Politics");
        inMain All = new inMain();
        Main.removeAll();
        Main.add(All).setVisible(true);
        All.setBounds(0, 0, Main.getWidth(), Main.getHeight());
    }//GEN-LAST:event_label5MouseClicked

    private void label6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label6MouseClicked
        Library.setGenere("Poetry");
        inMain All = new inMain();
        Main.removeAll();
        Main.add(All).setVisible(true);
        All.setBounds(0, 0, Main.getWidth(), Main.getHeight());
    }//GEN-LAST:event_label6MouseClicked
    
    private void label7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label7MouseClicked
        Library.setGenere("History");
        inMain All = new inMain();
        Main.removeAll();
        Main.add(All).setVisible(true);
        All.setBounds(0, 0, Main.getWidth(), Main.getHeight());
    }//GEN-LAST:event_label7MouseClicked

    private void label8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label8MouseClicked
        Library.setGenere("Computer Science");
        inMain All = new inMain();
        Main.removeAll();
        Main.add(All).setVisible(true);
        All.setBounds(0, 0, Main.getWidth(), Main.getHeight());
    }//GEN-LAST:event_label8MouseClicked
    
    private void label9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label9MouseClicked
        Library.setGenere("Novels");
        inMain All = new inMain();
        Main.removeAll();
        Main.add(All).setVisible(true);
        All.setBounds(0, 0, Main.getWidth(), Main.getHeight());
    }//GEN-LAST:event_label9MouseClicked

    private void label10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label10MouseClicked
        Library.setGenere("Horror");
        inMain All = new inMain();
        Main.removeAll();
        Main.add(All).setVisible(true);
        All.setBounds(0, 0, Main.getWidth(), Main.getHeight());
    }//GEN-LAST:event_label10MouseClicked

    private void label11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label11MouseClicked
        Library.setGenere("Romance");
        inMain All = new inMain();
        Main.removeAll();
        Main.add(All).setVisible(true);
        All.setBounds(0, 0, Main.getWidth(), Main.getHeight());
    }//GEN-LAST:event_label11MouseClicked

    private void label12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label12MouseClicked
        Library.setGenere("Arts");
        inMain All = new inMain();
        Main.removeAll();
        Main.add(All).setVisible(true);
        All.setBounds(0, 0, Main.getWidth(), Main.getHeight());
    }//GEN-LAST:event_label12MouseClicked

    
    
    public void setColor(JPanel p1, JLabel l1) {
        changecolor(p1, new Color(72, 128, 242));
        l1.setForeground(new Color(255, 255, 255));
    }
    
    public void resetColor(JPanel p1, JLabel l1) {
        changecolor(p1, new Color(35, 40, 72));
        l1.setForeground(new Color(160, 166, 204));
    }
    
    private void label1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseEntered
        setColor(panel1, label1);
    }//GEN-LAST:event_label1MouseEntered
    
    private void label1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseExited
        resetColor(panel1, label1);
    }//GEN-LAST:event_label1MouseExited
    
    private void label2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseEntered
        // TODO add your handling code here:
        setColor(panel2, label2);
    }//GEN-LAST:event_label2MouseEntered
    
    private void label2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseExited
        resetColor(panel2, label2);
    }//GEN-LAST:event_label2MouseExited
     
    private void label3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MouseEntered
        setColor(panel3, label3);
    }//GEN-LAST:event_label3MouseEntered
    
    private void label3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MouseExited
        resetColor(panel3, label3);
    }//GEN-LAST:event_label3MouseExited
    
    private void label4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MouseEntered
        setColor(panel4, label4);
    }//GEN-LAST:event_label4MouseEntered
    
    private void label4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MouseExited
        resetColor(panel4, label4);
    }//GEN-LAST:event_label4MouseExited
    
    private void label5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MouseEntered
        setColor(panel5, label5);
    }//GEN-LAST:event_label5MouseEntered
    
    private void label5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MouseExited
        resetColor(panel5, label5);
    }//GEN-LAST:event_label5MouseExited
    
    private void label6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label6MouseEntered
        setColor(panel6, label6);
    }//GEN-LAST:event_label6MouseEntered
    
    private void label6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label6MouseExited
        resetColor(panel6, label6);
    }//GEN-LAST:event_label6MouseExited
    
    private void label7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label7MouseEntered
        setColor(panel7, label7);
    }//GEN-LAST:event_label7MouseEntered
    
    private void label7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label7MouseExited
        resetColor(panel7, label7);
    }//GEN-LAST:event_label7MouseExited
    
    private void label8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label8MouseEntered
        setColor(panel8, label8);
    }//GEN-LAST:event_label8MouseEntered
    
    private void label8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label8MouseExited
        resetColor(panel8, label8);
    }//GEN-LAST:event_label8MouseExited
    
    private void label9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label9MouseEntered
        setColor(panel9, label9);
    }//GEN-LAST:event_label9MouseEntered
    
    
    private void label9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label9MouseExited
        resetColor(panel9, label9);
    }//GEN-LAST:event_label9MouseExited
    
    private void label10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label10MouseEntered
        setColor(panel10, label10);
    }//GEN-LAST:event_label10MouseEntered
    
    private void label10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label10MouseExited
        resetColor(panel10, label10);
    }//GEN-LAST:event_label10MouseExited
    
    private void label11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label11MouseEntered
        setColor(panel11, label11);
    }//GEN-LAST:event_label11MouseEntered
    
    private void label11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label11MouseExited
        resetColor(panel11, label11);
    }//GEN-LAST:event_label11MouseExited
    
    private void label12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label12MouseEntered
        setColor(panel12, label12);
    }//GEN-LAST:event_label12MouseEntered
    
    private void label12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label12MouseExited
        resetColor(panel12, label12);
    }//GEN-LAST:event_label12MouseExited
    
    private void titlebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_titlebarMouseReleased

    private void titlebarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMouseEntered
        titlebar.setVisible(true);
    }//GEN-LAST:event_titlebarMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        changecolor(ButtonMin, new Color(83, 103, 255));
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        changecolor(ButtonMin, new Color(25, 29, 74));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setExtendedState(Mainmenu.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void fullmaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullmaxMouseExited
        changecolor(Buttonmax, new Color(83, 103, 255));
    }//GEN-LAST:event_fullmaxMouseExited

    private void fullmaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullmaxMouseEntered
        changecolor(Buttonmax, new Color(25, 29, 74));
    }//GEN-LAST:event_fullmaxMouseEntered

    private void fullmaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullmaxMouseClicked
        if(this.getExtendedState()!= Mainmenu.MAXIMIZED_BOTH){
            this.setExtendedState(Mainmenu.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(Mainmenu.NORMAL);
        }
    }//GEN-LAST:event_fullmaxMouseClicked

    

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        changecolor(Buttonclose, new Color(83, 103, 255));
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        changecolor(Buttonclose, new Color(25, 29, 74));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseDragged

    private void viewProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewProfileMouseClicked
        if(Library.isIsAdmin()) {
            ProfileAdmin main = new ProfileAdmin();
            main.setVisible(true);
        }
        else {
            Profile main = new Profile() ; 
            main.setVisible(true);
        }
    }//GEN-LAST:event_viewProfileMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        FavBooks main = new FavBooks();
        main.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainmenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonMin;
    private javax.swing.JPanel Buttonclose;
    private javax.swing.JPanel Buttonmax;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Icon;
    private javax.swing.JDesktopPane Main;
    private javax.swing.JLabel close;
    private javax.swing.JPanel dashboardview;
    private javax.swing.JLabel fullmax;
    private javax.swing.JPanel iconminmaxclose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel10;
    private javax.swing.JPanel panel11;
    private javax.swing.JPanel panel12;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JPanel panel6;
    private javax.swing.JPanel panel7;
    private javax.swing.JPanel panel8;
    private javax.swing.JPanel panel9;
    private java.awt.Scrollbar scrollbar1;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel titlebar;
    private javax.swing.JLabel viewProfile;
    // End of variables declaration//GEN-END:variables

}
