
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;


public class ProfileAdmin extends javax.swing.JFrame {

    public ProfileAdmin() {
        initComponents();
        try {
            Tools.connectionToSql();
            txtUsername.setText(Library.getUsernameId());
            txtEmail.setText(Library.getEmailId());
            txtPhone.setText(Library.getPhoneId());
            txtName.setText(Library.getNameId());
            System.out.println(Library.getPathId());
            
            imgShow.setIcon(ResizeImage(Library.getPathId()));
            txtGender.setText(Library.getGenderId() == 'M'? "Male": "Female");
            JLabel label =new JLabel("HELLO HI");
            
        } catch(Exception Ex) {
            
        }
    }
    
    public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(220, 290,Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlebar = new javax.swing.JPanel();
        iconminmaxclose = new javax.swing.JPanel();
        Buttonclose = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        ButtonMin = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        UserPhoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        EditButton = new javax.swing.JPanel();
        EditProfile = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtGender = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        imgShow = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        viewCus = new javax.swing.JPanel();
        viewCustomers = new javax.swing.JLabel();
        viewBo = new javax.swing.JPanel();
        viewBooks = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        titlebar.setBackground(new java.awt.Color(83, 103, 255));
        titlebar.setPreferredSize(new java.awt.Dimension(800, 40));
        titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                titlebarMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                titlebarMouseReleased(evt);
            }
        });
        titlebar.setLayout(new java.awt.BorderLayout());

        iconminmaxclose.setBackground(new java.awt.Color(83, 103, 255));
        iconminmaxclose.setPreferredSize(new java.awt.Dimension(150, 50));
        iconminmaxclose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buttonclose.setBackground(new java.awt.Color(83, 103, 255));
        Buttonclose.setLayout(new java.awt.BorderLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete_32px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        Buttonclose.add(close, java.awt.BorderLayout.CENTER);

        iconminmaxclose.add(Buttonclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 40));

        ButtonMin.setBackground(new java.awt.Color(83, 103, 255));
        ButtonMin.setLayout(new java.awt.BorderLayout());

        minimize.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        minimize.setForeground(new java.awt.Color(242, 242, 242));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        ButtonMin.add(minimize, java.awt.BorderLayout.CENTER);

        iconminmaxclose.add(ButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 40));

        titlebar.add(iconminmaxclose, java.awt.BorderLayout.LINE_END);

        getContentPane().add(titlebar, java.awt.BorderLayout.PAGE_END);

        main.setBackground(new java.awt.Color(38, 42, 66));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        main.add(UserPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Username:");
        main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, 40));

        txtUsername.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(242, 242, 242));
        txtUsername.setText("Peter_torki");
        main.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 310, 60));

        EditButton.setBackground(new java.awt.Color(0, 141, 190));
        EditButton.setForeground(new java.awt.Color(0, 133, 206));
        EditButton.setLayout(new java.awt.BorderLayout());

        EditProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EditProfile.setForeground(new java.awt.Color(242, 242, 242));
        EditProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditProfile.setText("Edit profile");
        EditProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditProfileMouseExited(evt);
            }
        });
        EditButton.add(EditProfile, java.awt.BorderLayout.CENTER);

        main.add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 160, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Name:");
        main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, 40));

        txtName.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(242, 242, 242));
        txtName.setText("Peter Joseph");
        main.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 330, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Email:");
        main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 70, 40));

        txtEmail.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(242, 242, 242));
        txtEmail.setText("peter@gmail.com");
        main.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 340, 60));

        txtGender.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        txtGender.setForeground(new java.awt.Color(242, 242, 242));
        txtGender.setText("Male");
        main.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 140, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Gender:");
        main.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 90, 40));

        txtPhone.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(242, 242, 242));
        txtPhone.setText("01211036617");
        main.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 240, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Phone:");
        main.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 80, 40));

        imgShow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imgShow.setPreferredSize(new java.awt.Dimension(210, 290));
        main.add(imgShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 210, 290));

        jPanel2.setBackground(new java.awt.Color(0, 141, 190));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Profile");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        main.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 60));

        viewCus.setBackground(new java.awt.Color(0, 141, 190));
        viewCus.setForeground(new java.awt.Color(0, 133, 206));
        viewCus.setLayout(new java.awt.BorderLayout());

        viewCustomers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewCustomers.setForeground(new java.awt.Color(242, 242, 242));
        viewCustomers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewCustomers.setText("View Customers");
        viewCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        viewCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewCustomersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewCustomersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewCustomersMouseExited(evt);
            }
        });
        viewCus.add(viewCustomers, java.awt.BorderLayout.CENTER);

        main.add(viewCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 160, 30));

        viewBo.setBackground(new java.awt.Color(0, 141, 190));
        viewBo.setForeground(new java.awt.Color(0, 133, 206));
        viewBo.setLayout(new java.awt.BorderLayout());

        viewBooks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewBooks.setForeground(new java.awt.Color(242, 242, 242));
        viewBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewBooks.setText("View Books");
        viewBooks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        viewBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBooksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewBooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewBooksMouseExited(evt);
            }
        });
        viewBo.add(viewBooks, java.awt.BorderLayout.CENTER);

        main.add(viewBo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 160, 30));

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(718, 564));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    private void EditProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProfileMouseEntered
        changecolor(EditButton, new Color(204, 204, 204));
    }//GEN-LAST:event_EditProfileMouseEntered

    private void EditProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProfileMouseExited
        changecolor(EditButton, new Color(0, 133, 206));
    }//GEN-LAST:event_EditProfileMouseExited

    private void EditProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProfileMouseClicked
        this.dispose();
        EditProfile op = new EditProfile() ; 
        op.setVisible(true);
        
    }//GEN-LAST:event_EditProfileMouseClicked

    private void titlebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_titlebarMouseReleased

    private void titlebarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMouseEntered
        titlebar.setVisible(true);
    }//GEN-LAST:event_titlebarMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        changecolor(ButtonMin, new Color(83, 103, 255));
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        changecolor(ButtonMin, new Color(25, 29, 74));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setExtendedState(Mainmenu.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        changecolor(Buttonclose, new Color(83, 103, 255));
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        changecolor(Buttonclose, new Color(25, 29, 74));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void viewBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBooksMouseClicked
        bookTable main = new bookTable();
        main.setVisible(true);
    }//GEN-LAST:event_viewBooksMouseClicked

    private void viewBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBooksMouseEntered
        changecolor(viewBo, new Color(204, 204, 204));
    }//GEN-LAST:event_viewBooksMouseEntered

    private void viewBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBooksMouseExited
        changecolor(viewBo, new Color(0, 133, 206));
    }//GEN-LAST:event_viewBooksMouseExited

    private void viewCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewCustomersMouseClicked
        UserTable main = new UserTable();
        main.setVisible(true);
    }//GEN-LAST:event_viewCustomersMouseClicked

    private void viewCustomersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewCustomersMouseEntered
        changecolor(viewCus, new Color(204, 204, 204));
    }//GEN-LAST:event_viewCustomersMouseEntered

    private void viewCustomersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewCustomersMouseExited
        changecolor(viewCus, new Color(0, 133, 206));
    }//GEN-LAST:event_viewCustomersMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonMin;
    private javax.swing.JPanel Buttonclose;
    private javax.swing.JPanel EditButton;
    private javax.swing.JLabel EditProfile;
    private javax.swing.JLabel UserPhoto;
    private javax.swing.JLabel close;
    private javax.swing.JPanel iconminmaxclose;
    private javax.swing.JLabel imgShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel main;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel titlebar;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPhone;
    private javax.swing.JLabel txtUsername;
    private javax.swing.JPanel viewBo;
    private javax.swing.JLabel viewBooks;
    private javax.swing.JPanel viewCus;
    private javax.swing.JLabel viewCustomers;
    // End of variables declaration//GEN-END:variables
}
